dataset:
  raw_data_path: 'artifacts/raw_data'
  raw_roi_path: 'artifacts/roi_data'
  output_data_path:
  output_roi_path:
  label: ['eyebrows', 'left', 'right', 'both', 'teeth']
  filepath_format: '{subject_id}/{label}/{position}_{trial}.csv'